version: "3.7"
services:
    app:
        build:
            args:
                user: rayhan
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: ishara-backend
        container_name: ishara-backend-container
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        environment:
            - DB_CONNECTION=mysql
            - DB_HOST=${DB_HOST}
            - DB_PORT=3306
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
        networks:
            - ishara-backend

    nginx:
        image: nginx:alpine
        container_name: ishara-backend-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        networks:
            - ishara-backend

networks:
    ishara-backend:
        driver: bridge
